[role="pagenumrestart"]
[[flaws_chapter]]
= Smart contract security flaws

This section contains my research on ethereum smart contracts security flaws


[[first_taxonomy]]
== A first insight
The paper "Smart Contract: Attacks and Protections" classifies the attack on smart contracts into 4 categories.
Then it explains the different attack techniques concerning application bugs.
Finally it presents the different analysis tools and exposed their limitations.

The analysis tool part of the paper will be discussed in the https://github.com/Longferret/smart_contract_tax/blob/main/tools.adoc[Analysis Tool section].

Link:: 
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8976179

[[attack_classification]]
=== Attack classification
Malicious acts:: The goal of the attack is to comprise the action of spreading malware to deceive users
Weak protocol:: It is a direct attack on the protocol, like the 51% attack.
Defraud:: The goal of the attack is to spend multiple time the same money by convicing the other party to approve the transaction too early (not enough confirmation by the network).
Application bugs:: Contains all security flaws related to human errors while coding.

[[attack_techniques]]
=== Application bugs attack techniques
Reentrancy:: A reentrancy attack happens when a function is externally invoked during its execution, allowing it to be run multiple times in a single transaction.
Overflow/Underflow:: The attack can occur on smart contracts that do not check their inputs.
An overflow in when an input value is greater than the maximum value the program can handle.
An underflow is the opposite, the input value is lower than the minimum value, this can cause the value to become really large.
Short Address Attack:: https://medium.com/coinmonks/understanding-and-preventing-short-address-attacks-in-solidity-smart-contracts-3d46a4af9a15

TO EXPLAIN

DelegateCall:: delegatecall is a low level function. It can allow an attacker to execute arbitrary code on a contract. This is because delegatecall executes the code of the called contract in the context of the calling contract, which means that the called contract can access and modify the storage variables of the calling contract.
Default Visibilities:: This kind of attack happends when a variable that should be accessible is accessible on any part of the code.
Transaction ordering dependence:: It happends when a smart contract is dependent on the transaction order.
A malicious miner could re-order transaction to change the outcome of multiple transactions.
Timestamp dependence:: This vulnerability is due to the ethereum network being asynchronous. If the smart contract is dependent on timestamps, a malicious miner could re-arrange the timestamp by a few seconds to change the outcome of a transaction. 

[[recent_taxonomy]]
== A recent open-source taxonomy
The authors created an open source taxonomy on smart contracts security flaws based on previous  taxonomies.
They called their taxonomy OpenCSV and it is available online. 

Links:: 
* Paper: https://arxiv.org/pdf/2303.14523.pdf
* OpenCSV: https://openscv.dei.uc.pt/

This taxonomy is very complete and recent (April 2023), It makes it an excellent tool to check for vulnerabilities in smart contracts.

We must note that the taxonomy presented in the paper is not anymore the same as the one online.

The part 4. "Bad Programming Pratices & Language Weakness" is now splitted in 2 categories: 

* Bad Programming Pratices & Language Weakness
* Erroneous Credit Transfer

MUST VERIFY FURTHER ALL SECURITY FLAWS
