[role="pagenumrestart"]
[[whatis_chapter]]
= Parsing the blockchain
This section contains my methods and what I learned on how to parse the Ethereum blockchain to find security flaws in smart contracts.

[[methodology]]
== Methodology
There are multiple way to parse the ethereum blockchain like:

* The Ethereum dataset from Google BigQuery
* TheGraph indexer
* Having an archive node

My choice to parse the blockchain is to have my own node.
The reason is that using the 2 first methods to parse the blockchain require a third party which can limit the number of queries or totaly block the access.
With my own node, I have everything on my hard drive.

There is just one problem, it is not possible for me to have an archive node, which contains every transaction since ethereum genesis because it is requires more than 13TB.
I'am going to run a full node which contains only the 128 last blocks and is approximately 1TB.

source: https://www.quicknode.com/guides/infrastructure/node-setup/ethereum-full-node-vs-archive-node

Note: I'am using an external 2TB SSD T7 shield from samsung

[[client_choice]]
=== Client Choice
To run a node on the Ethereum blockchain, one needs an execution client and a consensus client.

* The execution client is responsible for all new transactions broadcasted in the network, it executes them in EVM, and holds the latest state and database of all current Ethereum data.
* The consensus client implements the proof-of-stake consensus algorithm.

source: https://ethereum.org/en/developers/docs/nodes-and-clients/

There are different execution and consensus clients.

My choice for the execution client is Go Ethereum (Geth).
I chose it because it is the most popular execution client and is there since the beginning of ethereum.
It is written in Go and fully open-source.

My choice for the consensus client is Lighthouse for the same reasons.
It is there from the genesis of the beacon chain and is the most popular one.
It is written in Rust.

[[set_up_node]]
=== Setting up my node
Install the execution client: https://geth.ethereum.org/docs/getting-started

Install the consensus client: https://lighthouse-book.sigmaprime.io/installation.html

I will normally have enough disk space to have a full node on my ssd and
I plan to let it run on an old computer.

[[node_anamysis]]
== Node analysis
Everything I will do after I installed a full node.

https://rockset.com/blog/how-to-query-the-ethereum-blockchain/

[[query_blockchain]]
=== Simple Query
I will explain here my first queries to get smart contract data.
